### PR TITLE
prevent auto creating wallets on non-new accounts

### PR DESCRIPTION
**Pull request by wolverineks**
no visual changes

### CODE REVIEW

**Review by swansontec — COMMENTED** [review]
This seems fine to me, but it does mean that users can delete all their wallets, and the account will simply stay empty. Before, we would create the default wallets whenever the list is empty.

This could potentially cause a problem where we fail to create the wallets on first login, and then we never create the wallets, because the account is no longer "new". Before, we would recover from this case.

Maybe we could change the logic to include a check for `EdgeAccount.allKeys.length <= 2`, and then create the wallets in that case. That way, deleted wallets won't trigger new wallets to be created, but we can still recover from botched account creations.

**Comment by swansontec** [comment]
I would like @paullinator to read my review summary and give a yay or nay on the proposed change, or just leave it as-is.

**Comment by paullinator** [comment]
> I would like @paullinator to read my review summary and give a yay or nay on the proposed change, or just leave it as-is.

I totally agree with your summary. When servers are busy, we will frequently fail to create one or two of the wallets and it would be good to properly clean up the next time a user logs in.

**Comment by wolverineks** [comment]
what about something like?
```ts
if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:Bitcoin'))) 
  createWallet(account, 'BTC')
if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:Ethereum')))
  createWallet(account, 'ETH')
if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:BitcoinCash'))) 
  createWallet(account, 'BCH')
```

**Comment by paullinator** [comment]
> what about something like?
> 
> ```ts
> if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:Bitcoin'))) 
>   createWallet(account, 'BTC')
> if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:Ethereum')))
>   createWallet(account, 'ETH')
> if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:BitcoinCash'))) 
>   createWallet(account, 'BCH')
> ```

I am good with this suggestion, just double check the wallet types. I think they are always lowercase and Bitcoin might have a suffix

**Comment by swansontec** [comment]
> what about something like?
> 
> ```ts
> if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:Bitcoin'))) 
>   createWallet(account, 'BTC')
> if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:Ethereum')))
>   createWallet(account, 'ETH')
> if (!account.allKeys.find(({ walletType ) => walletType === 'wallet:BitcoinCash'))) 
>   createWallet(account, 'BCH')
> ```

This works, specifically, because `allKeys` includes deleted wallets as well. So, we create each one at least once, and then never again. But, the wallet types should be double-checked for spelling, as mentioned.

**Review by swansontec — APPROVED** [review]
This looks good. I will merge once its rebased onto develop.

**Comment by swansontec** [comment]
@wolverineks I can merge this once it's rebased onto the fresh `develop`.

**Pull request merged**
