### PR TITLE
Stuck spinning if all wallets are deleted

### PR DESCRIPTION
**Pull request by dbo1dyrev**

### CODE REVIEW

**Comment by thehobbit85** [comment]
The code looks good, but can you just add some screenshots?
You should always add screenshots of the App when you make any changes that adds/removes/changes the design in any way.

**Comment by dbo1dyrev** [comment]
Screenshot 2021-05-14 at 12 34 04

**Review by thehobbit85 — CHANGES_REQUESTED** [review]
Actually, now that I see it, can you please split the text after the dot and add a 1 rem spacing between the first and the second line like this?

```
Edge requires at least one wallet in this account. 

If you’d like to delete this wallet, you’ll need to add an additional wallet(s) to this account.
```

I know that's not what the design showed but this looks very crowded.

**Comment by dbo1dyrev** [comment]
Screenshot 2021-05-14 at 13 39 20
Like this?

**Comment by paullinator** [comment]
Please change the text to remove the “(s)” at the end of “wallet”. Having this doesn’t translate well.

**Comment by dbo1dyrev** [comment]
Screenshot 2021-05-17 at 10 25 19

**Review by thehobbit85 — APPROVED** [review]

**Pull request merged**
