### PR TITLE
Add back DotsBackground to SceneWrapper

### PR DESCRIPTION
**Pull request by paullinator**
### CHANGELOG

Does this branch warrant an entry to the CHANGELOG?

- [x] Yes
- [ ] No

### Dependencies

 none

### Requirements

If you have made **any** visual changes to the GUI. Make sure you have:

- [x] Tested on iOS device
- [x] Tested on Android device
- [x] Tested on small-screen device (iPod Touch)
- [x] Tested on large-screen device (tablet)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206513324458918

### CODE REVIEW

**Comment by paullinator** [comment]
Screenshot 2024-02-03 at 15 03 38
Screenshot 2024-02-03 at 15 03 57
Screenshot 2024-02-03 at 15 04 24
Screenshot 2024-02-03 at 15 04 41
-f691-46ae-9013-6be5372f329e">
Screenshot 2024-02-03 at 15 05 16
Screenshot 2024-02-03 at 15 06 26
Screenshot 2024-02-03 at 15 06 58

**Comment by paullinator** [comment]
Screenshot 2024-02-03 at 15 09 28
Screenshot 2024-02-03 at 15 09 46
Screenshot 2024-02-03 at 15 09 57

**Comment by paullinator** [comment]
Screenshot 2024-02-03 at 15 35 16
Screenshot 2024-02-03 at 15 35 45
Screenshot 2024-02-03 at 15 36 13
Screenshot 2024-02-03 at 15 36 51
Screenshot 2024-02-03 at 15 37 08
Screenshot 2024-02-03 at 15 37 32
Screenshot 2024-02-03 at 15 37 51
Screenshot 2024-02-03 at 15 38 29
Screenshot 2024-02-03 at 15 38 51
Screenshot 2024-02-03 at 15 40 18
Screenshot 2024-02-03 at 15 41 18
Screenshot 2024-02-03 at 15 41 40

**Comment by paullinator** [comment]
Screenshot 2024-02-03 at 15 42 49
Screenshot 2024-02-03 at 15 43 23
Screenshot 2024-02-03 at 15 43 41
Screenshot 2024-02-03 at 15 43 53
Screenshot 2024-02-03 at 15 44 03
Screenshot 2024-02-03 at 15 44 15
Screenshot 2024-02-03 at 15 44 28
Screenshot 2024-02-03 at 15 44 40
Screenshot 2024-02-03 at 15 45 25
Screenshot 2024-02-03 at 15 45 53
Screenshot 2024-02-03 at 15 46 04
Screenshot 2024-02-03 at 15 46 17

**Review by samholmes — APPROVED** [review]

**Pull request merged**
