### PR TITLE
Jacob/defaultfeesetting

### PR DESCRIPTION
**Pull request by jacobburrell**
#### PR Requirements

If you have made **any** visual changes to the GUI. Make sure you have:
- [ ] Tested on iOS Tablet
- [ ] Tested on small Android
- [ x ] Tested on iOS Simulator

### CODE REVIEW

**Comment by jacobburrell** [comment]
@thehobbit85 Had to rebase and merge a whole lot of incoming changes that touched the same scenes and reducers I modified.

Please double-check I merged correctly here.

**Comment by jacobburrell** [comment]
Squashed commits and rebased.

**Review by thehobbit85 — CHANGES_REQUESTED** [review]
@jacobburrell They tests are failing. You need to make sure the PR can pass the tests before you submit it.

**Comment by jacobburrell** [comment]
Made a new branch to implement changes from scratch.

**Pull request closed without merging**
